- name: Check if RKE2 uninstall script exists
  ansible.builtin.stat:
    path: /usr/local/bin/rke2-uninstall.sh
  register: rke2_uninstall_script

- name: Run RKE2 uninstall script if it exists
  become: true
  ansible.builtin.command: /usr/local/bin/rke2-uninstall.sh
  when: rke2_uninstall_script.stat.exists
  ignore_errors: true

- name: Manual cleanup if uninstall script doesn't exist
  become: true
  block:
    - name: Stop RKE2 services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - rke2-server
        - rke2-agent
      ignore_errors: true

    - name: Remove RKE2 directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/rke2
        - /var/lib/rancher/rke2
        - /var/lib/kubelet
        - /var/lib/rancher/rke2-agent
        - /var/lib/rancher/rke2-server
        - /run/k3s
        - /run/flannel
        - /etc/kubernetes
        - /var/run/kubernetes

    - name: Remove RKE2 binary
      ansible.builtin.file:
        path: /usr/local/bin/rke2
        state: absent

    - name: Remove kubectl symlink
      ansible.builtin.file:
        path: /usr/local/bin/kubectl
        state: absent
  when: not rke2_uninstall_script.stat.exists
